import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Nunito({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={font.className}
        >
          <Toaster/>
          <ExitModal/>
          <HeartsModal/>
          {children}
        </body>
      </html>
    </ClerkProvider>
    
  );
}
